title:              Super-Z Blog
email:              zhichaozhang829@163.com
description:        记录科研学习的思考与生活体验的点滴
author:             Start Bootstrap
baseurl:            "/blog"
url:                "https://zhic-z.github.io/"

# Social Profiles
twitter_username:   
github_username:    Zhic-Z
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
